import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import { bundledThemes } from 'shiki/themes';

const { default: githubLight } = await bundledThemes['github-light']();

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
// Read the local reader without modifying its workspace.
const reader = '/home/pi/work/ea-md-reader';
const source = postcss.parse(await readFile(join(reader, 'src/markdown.css'), 'utf8'));
const app = postcss.parse(await readFile(join(reader, 'src/app.css'), 'utf8'));
const output = postcss.root();
output.append(postcss.comment({ text: 'Generated by typora_ea_reader: npm run build. Reading styles: ea-md-reader/src/markdown.css + src/app.css; editor styles: typora_ea_reader/src/typora.css. MIT, yceachan. Do not edit this output.' }));

const unused = new Set(['--kb-nav-height', '--kb-sidebar-width', '--kb-profile-surface', '--kb-weight-regular', '--radius']);
const fences = '#write .md-fences:not(.md-fences-advanced), #write .md-fences-advanced.md-focus';

function selectorFor(selector) {
  if (selector === ':root') return selector;
  if (selector === '.frontmatter-block pre') return '#write .md-meta-block';
  if (selector === '.frontmatter-block' || /\.shiki|\.broken-image|\.callout|\.mermaid-error/.test(selector)) return null;
  if (selector === '.vp-doc pre') return fences;
  if (selector === '.vp-doc pre code') return '#write .md-fences code';
  if (selector === '.vp-doc ul.contains-task-list') return '#write ul.task-list';
  if (selector === '.vp-doc li.task-list-item') return null; // Typora positions editable checkboxes itself.
  if (selector.includes('.task-list-item-checkbox')) return '#write .md-task-list-item > input';
  if (selector.includes('.mermaid')) return selector.replace('.vp-doc .mermaid', '#write [lang="mermaid"] .md-diagram-panel');
  if (selector.includes('.github-alert')) {
    return selector.replace('.vp-doc', '#write')
      .replace(/\.custom-block\.(\w+)\.github-alert/g, (_, type) => `.md-alert.md-alert-${type === 'danger' ? 'caution' : type}`)
      .replace('.custom-block.github-alert', '.md-alert')
      .replace('.custom-block-title', '.md-alert-text');
  }
  return selector.replace('.vp-doc', '#write');
}

source.walkRules((original) => {
  const selectors = [...new Set(original.selectors.map(selectorFor).filter(Boolean))];
  if (!selectors.length) return;
  const rule = original.clone({ selector: selectors.join(',\n') });
  // Include reader overrides before adapting its rendered HTML to Typora's DOM.
  app.walkRules((override) => {
    if (override.selector === original.selector) {
      override.walkDecls((decl) => {
        const existing = rule.nodes.find((node) => node.type === 'decl' && node.prop === decl.prop);
        if (existing) existing.value = decl.value;
        else rule.append(decl.clone());
      });
    }
  });
  rule.walkDecls((decl) => {
    if (unused.has(decl.prop)) decl.remove();
    else if (decl.prop === 'font-size') {
      decl.value = decl.value.replace(/(\d+(?:\.\d+)?)px/g, (_, px) => `${Number(px) / 16}rem`);
      if (original.selector === '.vp-doc') decl.value = '1rem';
    }
    if (original.selector === '.vp-doc table' && ['display', 'overflow-x', 'margin'].includes(decl.prop)) decl.remove();
    if (original.selector.includes('.task-list-item-checkbox') && ['margin-top', 'flex'].includes(decl.prop)) decl.remove();
    if (original.selector === '.vp-doc pre' && decl.prop === 'overflow-x') decl.remove(); // Keep CodeMirror's editing overlays visible.
    if (original.selector === '.vp-doc img' && decl.prop === 'cursor') decl.remove();
    if (original.selector.includes('.custom-block-title') && decl.prop === 'color') decl.important = true;
  });
  rule.raws.before = '\n\n';
  output.append(rule);
});

// Keep CodeMirror colors sourced from the same GitHub Light palette as Shiki.
const syntax = [
  ['comment', '.cm-comment'],
  ['constant', '.cm-atom, .cm-number, .cm-variable-2, .cm-property, .cm-attribute'],
  ['keyword', '.cm-keyword'],
  ['string', '.cm-string, .cm-string-2'],
  ['entity.name.tag', '.cm-tag'],
  ['entity.name', '.cm-def, .cm-variable-3'],
];
for (const [scope, targets] of syntax) {
  const token = githubLight.tokenColors.find((entry) => (Array.isArray(entry.scope) ? entry.scope : [entry.scope]).includes(scope));
  if (!token?.settings.foreground) throw new Error(`GitHub Light palette has no color for ${scope}`);
  const selector = targets.split(', ').map((target) => `.cm-s-inner ${target}, .cm-s-typora-default ${target}`).join(',\n');
  output.append(postcss.rule({ selector, nodes: [postcss.decl({ prop: 'color', value: token.settings.foreground })], raws: { before: '\n\n' } }));
}
output.append(postcss.parse(await readFile(join(root, 'src/typora.css'), 'utf8')).nodes);

const destination = join(root, 'dist/ea-reader.css');
await mkdir(dirname(destination), { recursive: true });
await writeFile(destination, `${output.toString()}\n`);
await writeFile(join(root, 'dist/ea-reader.user.css'), await readFile(join(root, 'src/ea-reader.user.css')));
console.log(`Generated ${destination}`);
